export const fakedata: ServerInfoResponse = {
  hostname: 'Test Server',
  ip: '127.0.0.1',
  map: 'vsh_2towers',
  maxPlayers: 32,
  numPlayers: 18,
  players: [
    {
      steamID64: '76561198210264393',
      isSelf: true,
      name: 'TheEntireUIDevelopmentTeam',
      tags: [],
      localVerdict: 'Player',
      gameInfo: {
        deaths: 0,
        state: 'Joining',
        kills: 1,
        team: 3,
        loss: 0,
        ping: 40,
        userid: '0',
        time: 0,
      },
      steamInfo: {
        pfp: 'https://github.com/SammCheese.png',
        countryCode: 'X',
        timeCreated: 1318493205,
      },
    },
    {
      steamID64: '456822423554124',
      isSelf: false,
      name: 'Sammy',
      tags: [],
      localVerdict: 'None',
      gameInfo: {
        deaths: 0,
        state: 'Active',
        kills: 3,
        team: 3,
        loss: 0,
        ping: 40,
        userid: '0',
        time: 0,
      },
      steamInfo: {
        vacBans: 2,
        gameBans: 1,
        profileVisibility: 'Private',
        friends: [
          {
            steamID64: '76561198210264393',
            friendsSince: '34232',
          },
        ],
      },
    },
    {
      steamID64: '54822487235354124',
      isSelf: false,
      name: 'Woah So Cool!',
      tags: [],
      localVerdict: 'None',
      gameInfo: {
        deaths: 0,
        state: 'Active',
        kills: 0,
        team: 2,
        loss: 0,
        ping: 40,
        userid: '0',
        time: 0,
      },
      steamInfo: {
        gameBans: 2,
      },
    },
    {
      steamID64: '5842421335354124',
      isSelf: false,
      name: 'OptimusPrimus',
      tags: [],
      localVerdict: 'None',
      gameInfo: {
        deaths: 0,
        state: 'Active',
        kills: 0,
        team: 2,
        loss: 0,
        ping: 40,
        userid: '0',
        time: 0,
      },
      steamInfo: {
        gameBans: 1,
      },
    },
    {
      steamID64: '980724235354124',
      isSelf: false,
      name: 'Only Human',
      tags: [],
      localVerdict: 'Cheater',
      gameInfo: {
        deaths: 0,
        state: 'Active',
        kills: 0,
        team: 3,
        loss: 0,
        ping: 40,
        userid: '0',
        time: 0,
      },
      steamInfo: {
        vacBans: 1,
        profileVisibility: 'Friends Only',
      },
    },
    {
      steamID64: '3243595415354124',
      isSelf: false,
      name: 'Panzerwagenfahrer IV',
      tags: [],
      localVerdict: 'None',
      gameInfo: {
        deaths: 0,
        state: 'Joining',
        kills: 0,
        team: 2,
        loss: 0,
        ping: 40,
        userid: '0',
        time: 2300,
      },
    },
    {
      steamID64: '3297834415354124',
      isSelf: false,
      name: 'The Hearts of Iron',
      tags: [],
      localVerdict: 'None',
      gameInfo: {
        deaths: 0,
        state: 'Joining',
        kills: 0,
        team: 2,
        loss: 0,
        ping: 40,
        userid: '0',
        time: 2300,
      },
    },
    {
      steamID64: '32123854124',
      isSelf: false,
      name: 'Faker',
      tags: [],
      localVerdict: 'None',
      gameInfo: {
        deaths: 0,
        state: 'Joining',
        kills: 0,
        team: 2,
        loss: 0,
        ping: 40,
        userid: '0',
        time: 2300,
      },
    },
    {
      steamID64: '3241576574124',
      isSelf: false,
      name: 'DoesHotter',
      tags: [],
      localVerdict: 'Bot',
      gameInfo: {
        deaths: 0,
        state: 'Joining',
        kills: 0,
        team: 2,
        loss: 0,
        ping: 40,
        userid: '0',
        time: 2300,
      },
    },
    {
      steamID64: '324324124',
      isSelf: false,
      name: 'The Cool Person',
      tags: [],
      localVerdict: 'None',
      gameInfo: {
        deaths: 0,
        state: 'Joining',
        kills: 0,
        team: 2,
        loss: 0,
        ping: 40,
        userid: '0',
        time: 2300,
      },
    },
    {
      steamID64: '324234424',
      isSelf: false,
      name: 'Only Human',
      tags: [],
      localVerdict: 'None',
      gameInfo: {
        deaths: 0,
        state: 'Joining',
        kills: 0,
        team: 2,
        loss: 0,
        ping: 40,
        userid: '0',
        time: 2300,
      },
    },
  ],
};
